import { resolve, join } from 'node:path';
import { loadAgentManifest, loadFileIfExists } from '../utils/loader.js';
import { loadAllSkills, getAllowedTools } from '../utils/skill-loader.js';

/**
 * Export a gitagent directory to a LangChain-compatible Python agent script.
 *
 * Generates a ready-to-run Python file using the LangChain `create_tool_calling_agent`
 * pattern with a `ChatOpenAI` / `ChatAnthropic` backbone and an `AgentExecutor`.
 * Skills are surfaced as placeholder `@tool` functions; compliance constraints are
 * injected into the system prompt.
 */
export function exportToLangChain(dir: string): string {
  const agentDir = resolve(dir);
  const manifest = loadAgentManifest(agentDir);

  const systemPrompt = buildSystemPrompt(agentDir, manifest);
  const tools = buildToolDefinitions(agentDir);
  const modelImport = resolveModelImport(manifest.model?.preferred);

  const lines: string[] = [];

  lines.push('"""');
  lines.push(`LangChain agent for ${manifest.name} v${manifest.version}`);
  lines.push('Generated by gitagent export --format langchain');
  lines.push('"""');
  lines.push('');
  lines.push('from langchain.agents import create_tool_calling_agent, AgentExecutor');
  lines.push('from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder');
  lines.push('from langchain_core.tools import tool');
  lines.push(`${modelImport}`);
  lines.push('');

  // Tool stubs
  if (tools.length > 0) {
    lines.push('# --- Tools (implement or replace with real LangChain tools) ---');
    for (const t of tools) {
      const funcName = t.name.replace(/[^a-zA-Z0-9]/g, '_');
      lines.push('');
      lines.push('@tool');
      lines.push(`def ${funcName}(input: str) -> str:`);
      lines.push(`    """${t.description}"""`);
      lines.push(`    # TODO: implement tool logic`);
      lines.push(`    raise NotImplementedError("${funcName} not yet implemented")`);
    }
    lines.push('');
    lines.push(`tools = [${tools.map(t => t.name.replace(/[^a-zA-Z0-9]/g, '_')).join(', ')}]`);
  } else {
    lines.push('tools = []');
  }

  lines.push('');
  lines.push('# --- Model ---');
  lines.push(`llm = ${resolveModelInstantiation(manifest.model?.preferred)}`);
  lines.push('');
  lines.push('# --- Prompt ---');
  lines.push('prompt = ChatPromptTemplate.from_messages([');
  lines.push('    ("system", """' + systemPrompt.replace(/"""/g, '\\"\\"\\"') + '"""),');
  lines.push('    MessagesPlaceholder(variable_name="chat_history", optional=True),');
  lines.push('    ("human", "{input}"),');
  lines.push('    MessagesPlaceholder(variable_name="agent_scratchpad"),');
  lines.push('])');
  lines.push('');
  lines.push('# --- Agent ---');
  lines.push(`agent = create_tool_calling_agent(llm, tools, prompt)`);
  lines.push(`agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)`);
  lines.push('');
  lines.push('if __name__ == "__main__":');
  lines.push(`    print("Agent: ${manifest.name} v${manifest.version}")`);
  lines.push('    while True:');
  lines.push('        user_input = input("You: ").strip()');
  lines.push('        if not user_input or user_input.lower() in ("exit", "quit"):');
  lines.push('            break');
  lines.push('        result = agent_executor.invoke({"input": user_input})');
  lines.push('        print(f"Agent: {result[\'output\']}")') ;

  return lines.join('\n');
}

function buildSystemPrompt(agentDir: string, manifest: ReturnType<typeof loadAgentManifest>): string {
  const parts: string[] = [];

  const soul = loadFileIfExists(join(agentDir, 'SOUL.md'));
  if (soul) parts.push(soul);

  const rules = loadFileIfExists(join(agentDir, 'RULES.md'));
  if (rules) parts.push(`## Rules\n${rules}`);

  const skillsDir = join(agentDir, 'skills');
  const skills = loadAllSkills(skillsDir);
  for (const skill of skills) {
    const allowedTools = getAllowedTools(skill.frontmatter);
    const toolsNote = allowedTools.length > 0 ? `\nAllowed tools: ${allowedTools.join(', ')}` : '';
    parts.push(`## Skill: ${skill.frontmatter.name}\n${skill.frontmatter.description}${toolsNote}\n\n${skill.instructions}`);
  }

  if (manifest.compliance) {
    const c = manifest.compliance;
    const constraints: string[] = ['## Compliance Constraints'];
    if (c.communications?.fair_balanced) constraints.push('- All outputs must be fair and balanced (FINRA 2210)');
    if (c.communications?.no_misleading) constraints.push('- Never make misleading or promissory statements');
    if (c.data_governance?.pii_handling === 'redact') constraints.push('- Redact all PII from outputs');
    if (c.supervision?.human_in_the_loop === 'always') constraints.push('- All decisions require human approval');
    if (constraints.length > 1) parts.push(constraints.join('\n'));
  }

  return parts.join('\n\n');
}

interface ToolDef {
  name: string;
  description: string;
}

function buildToolDefinitions(agentDir: string): ToolDef[] {
  const skills = loadAllSkills(join(agentDir, 'skills'));
  return skills.map(s => ({
    name: s.frontmatter.name,
    description: s.frontmatter.description ?? s.frontmatter.name,
  }));
}

function resolveModelImport(model?: string): string {
  if (!model) return 'from langchain_openai import ChatOpenAI';
  if (model.startsWith('claude')) return 'from langchain_anthropic import ChatAnthropic';
  if (model.startsWith('gemini')) return 'from langchain_google_genai import ChatGoogleGenerativeAI';
  return 'from langchain_openai import ChatOpenAI';
}

function resolveModelInstantiation(model?: string): string {
  if (!model) return 'ChatOpenAI(model="gpt-4o", temperature=0.3)';
  if (model.startsWith('claude')) return `ChatAnthropic(model="${model}", temperature=0.3)`;
  if (model.startsWith('gemini')) return `ChatGoogleGenerativeAI(model="${model}", temperature=0.3)`;
  return `ChatOpenAI(model="${model}", temperature=0.3)`;
}