"""
LangGraph definition for research-assistant v1.0.0
Generated by gitagent export --format langgraph
"""

from __future__ import annotations

from typing import Annotated, TypedDict

from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage
from langchain_core.tools import tool
from langchain.chat_models import init_chat_model
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode

# Agent metadata
AGENT_NAME = "research-assistant"
AGENT_VERSION = "1.0.0"
AGENT_DESCRIPTION = "Two-step research assistant — searches the web, then summarizes findings"
MODEL = "claude-sonnet-4-5"
RECURSION_LIMIT = 25

# System prompt (SOUL.md + RULES.md + DUTIES.md + compliance)
SYSTEM_PROMPT = """# research-assistant
Two-step research assistant — searches the web, then summarizes findings

# Research Assistant

You are a research assistant. Find authoritative sources, extract the relevant
facts, and summarize them honestly. Cite every claim. When uncertain, say so.
"""

# Skill instructions
SKILL_SUMMARIZE_INSTRUCTIONS = """Condense the gathered sources into a faithful, cited summary

Produce a concise summary of the gathered material. Every factual claim must
be attributed to a specific source URL. If the sources disagree, say so
explicitly rather than picking a side."""

SKILL_WEB_RESEARCH_INSTRUCTIONS = """Search the web for sources relevant to the user's question
Allowed tools: web-search

Use the `web-search` tool to find authoritative sources. Prefer primary sources
(official docs, academic papers) over secondary commentary. Capture the URL of
every source consulted."""

# Graph state
class AgentState(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]

# Tools (from tools/*.yaml)
@tool
def web_search(query: str) -> str:
    """Search the public web for a query"""
    raise NotImplementedError("Implement tool: web-search")

TOOLS = [web_search]
tool_node = ToolNode(TOOLS)

llm = init_chat_model(MODEL)
llm_with_tools = llm.bind_tools(TOOLS) if TOOLS else llm

# Hooks (pre_tool_use → before_tool callback)
def before_tool(state: AgentState) -> AgentState:
    """No pre_tool_use hooks configured in hooks/hooks.yaml."""
    return state

# NOTE: post_tool_use, on_session_start, etc. have no LangGraph equivalent — skipped.
# NOTE: memory/ has no direct LangGraph equivalent — implement via a checkpointer.

# Skill nodes (one per skills/<name>/SKILL.md)
def skill_summarize(state: AgentState) -> dict:
    """Skill node: summarize — Condense the gathered sources into a faithful, cited summary"""
    prompt = SYSTEM_PROMPT + "\n\n" + SKILL_SUMMARIZE_INSTRUCTIONS
    messages = [SystemMessage(content=prompt), *state["messages"]]
    response = llm_with_tools.invoke(messages)
    return {"messages": [response]}

def skill_web_research(state: AgentState) -> dict:
    """Skill node: web-research — Search the web for sources relevant to the user's question"""
    prompt = SYSTEM_PROMPT + "\n\n" + SKILL_WEB_RESEARCH_INSTRUCTIONS
    messages = [SystemMessage(content=prompt), *state["messages"]]
    response = llm_with_tools.invoke(messages)
    return {"messages": [response]}

# Graph construction
graph = StateGraph(AgentState)

graph.add_node("tools", tool_node)

# Skillflow: research
graph.add_node("research", skill_web_research)
graph.add_node("summarize", skill_summarize)
graph.add_edge(START, "research")
graph.add_edge("research", "summarize")
graph.add_edge("summarize", END)


# Compile
app = graph.compile()

if __name__ == "__main__":
    result = app.invoke(
        {"messages": [HumanMessage(content="Hello")]},
        config={"recursion_limit": RECURSION_LIMIT},
    )
    for message in result["messages"]:
        print(message)
